### ISSUE TITLE
How to compat with binary files compatible with `riscv-none-embed`

### ISSUE THREAD

**Issue by dreamcmi** [xpack-dev-tools/riscv-none-elf-gcc-xpack#11]
Ready to upgrade the company's GCC to version 12. The previous use of the `riscv-none-embed-gcc-xpack` repo. The binary files generated by it are beginning of `riscv-none-embed`, but this repo is `riscv-none-elf` . If we want to be compatible with the old version through the file name, which files need to be modified to realize such demand?

**Comment by ilg-ul** [comment]
The old names prefixed with `riscv-none-embed-` are deprecated and **should not** be used for future projects, since there will be no further releases with these name.

I don't know your tools and your environment, but I don't think you can use your old projects unchanged, you have to edit them to update the file names, to the new `riscv-none-elf-` prefix.
